### ISSUE TITLE
Support für Symlinks

### ISSUE THREAD

**Issue by tristanlins** [menatwork/syncCto#186]
Wenn man composer im developer Modus betreibt, werden jede Menge Symlinks erzeugt. Diese sollten auch als Symlinks übertragen werden.

**Comment by stefanheimes** [comment]
Da wir in der Version 4 von SyncCto festgelegt haben, dass nur noch Inhalte Übertragen werden und wir keine Funktionen mehr für Composer bereitstellen, ist die Empfehlung alles über den Manager oder der Console zu machen.
