### ISSUE TITLE
Deprecated features in PHP 5.5.x - ext/mysql

### ISSUE THREAD

**Issue by stefanheimes** [menatwork/syncCto#200]
Source: http://www.php.net/manual/de/migration55.deprecated.php

**ext/mysql**

The original MySQL extension is now deprecated, and will generate E_DEPRECATED errors when connecting to a database. Instead, use the MySQLi or PDO_MySQL extensions.

**mcrypt**

The following functions have been deprecated:

mcrypt_cbc()
mcrypt_cfb()
mcrypt_ecb()
mcrypt_ofb()

**Comment by davidmaack** [comment]
Unter PHP 5.6 haben sich auch ein paar Änderungen ergeben:
http://de2.php.net/manual/de/migration56.incompatible.php

**Comment by stefanheimes** [comment]
Sollte mit denn neuen Versionen behoben sein.
