### ISSUE TITLE
Call to undefined function mcrypt_create_iv()

### ISSUE THREAD

**Issue by tristanlins** [menatwork/syncCto#210]
I got the following error `Fatal error: Call to undefined function mcrypt_create_iv() in .../composer/vendor/menatwork/ctocommunication/system/modules/ctoCommunication/CtoComCodifyengineImpl_AES.php on line 68` even when I configured syncCto to use phpseclib instead of mcrypt.

**Comment by stefanheimes** [comment]
Should be fix, with the newer versions.
