### ISSUE TITLE
Option to Exclude Domainname from Sync

### ISSUE THREAD

**Issue by christianromeni** [menatwork/syncCto#228]
I am currently using syncCto for dev/live deployment.
Dev is on dev.somedomain.de and live is on livedomain.de
I have a multiple domain setup and I am using the assets-URL and files-URL options.

So after every sync, I have to change them manually, since there is no way to disable this column from syncing.

I guess in the Pro-Version this option is given anyways, but isnt one of the reasons to have syncCto that there are several domains?

Would be realy nice to have at least this option in the basic version.

Thx :)

**Comment by stefanheimes** [comment]
Hi, 

you are right the pro version has such a function. But only for tl_page, tl_articel and tl_content.
If you need this for any other table or you don't want to buy the Pro Version there is another option. 

See https://github.com/menatwork/syncCto/wiki/3.-Hooks#syncdbupdatebeforedrop

With this hook you can copy the data from the original table to the temporary one with a little bit of sql code.
