### ISSUE TITLE
optionally allow sync of tl_files

### ISSUE THREAD

**Issue by fritzmg** [menatwork/syncCto#230]
`tl_files` is currently excluded by default when using the database sync. `tl_files` will only be transferred, if you use the "overwrite system" option.

It would be useful to optionally also allow the `tl_files` table to be transferred/compared when using the regular sync. e.g. as an additional option below "Database-synchronisation".

**Comment by frontendschlampe** [comment]
ähm ... there's already an option on top "Database synchronisation" with the possibility to sync ```tl_files```separately.

**Comment by stefanheimes** [comment]
I don't think so Jim.

**Comment by frontendschlampe** [comment]
"File manager (files)" is not this, what you want?

**Comment by stefanheimes** [comment]
Nope, we mean the tl_files table. This table is only overwrite wit the button  "overwrite system". You have no other chanse to do this.

**Comment by stefanheimes** [comment]
See https://github.com/menatwork/syncCto/issues/253
