### ISSUE TITLE
2.7.1, Windows, XAMPP: cannot create database backup

### ISSUE THREAD

**Issue by fritzmg** [menatwork/syncCto#236]
### Problem description

When trying to create a database backup with syncCto under Windows 7 and XAMPP 1.8.3 (PHP 5.5.11) and Contao 3.2.20, syncCto stops with the following error:
`
Invalid resource files\syncCto_backups\database\2015-06-04_1152_DB-Backup.zip
`
The file does exist however in that location. It works fine under 2.6.2.
### Analysis

It's either Contao's or syncCto's fault, depending on how you look at it ;). The problem is the  `Dbafs::addResource(…)` call within [SyncCtoModuleBackup](https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/SyncCtoModuleBackup.php#L400). It appears you are passing the path to the file like this:

```
files\syncCto_backups\database\2015-06-04_1152_DB-Backup.zip
```

i.e. with **backward slashes**. However, Contao's `Dbafs::addResource(…)` function does [this](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Dbafs.php#L54):

``` php
// The resource does not exist or lies outside the upload directory
if ($strResource == '' || strncmp($strResource,  $strUploadPath, strlen($strUploadPath)) !== 0 || !file_exists(TL_ROOT . '/' . $strResource))
{
    echo "foo";
    throw new \InvalidArgumentException("Invalid resource $strResource");
}
```

The problem is this part of the condition:

``` php
strncmp($strResource,  $strUploadPath, strlen($strUploadPath)) !== 0
```

It compares `files\` with `files/`, which results in `false` of course (or rather `false !== 0` will be true, naturally ;)). This is part of several problems with Contao under Windows, where Contao uses string compare or replacing functions of file paths which do not work with backward slashes. See contao/core-bundle#208
### Fix

Contao should probably not assume that the path only contains forward slashes - I'll document this case in contao/core-bundle#208 as well. But in the mean time, you should probably just make sure, that the path parameter for `Dbafs::addResource(…)` only contains forward slashes.

**Comment by stefanheimes** [comment]
I hvae to take a look at this. I start to use the DIRECTORY_SEPARATOR to solve such problems.... But it is hard to fix it.

**Comment by fritzmg** [comment]
It looks like this particular issue will be fixed within Contao in one of the next Contao 3.5 versions.
