### ISSUE TITLE
tng, 3.0.0-beta1: cannot create or import backups

### ISSUE THREAD

**Issue by fritzmg** [menatwork/syncCto#238]
In an installation I am using the following setup:
* `contao-community-alliance/dc-general` 	`dev-develop (b01c8e45)` → `2.0.x-dev`
* `menatwork/synccto` 	`3.0.0-beta1` (also tested with `dev-tng`)
* `metamodels/core` 	`dev-tng (f4fda245)` → `2.0.x-dev`
* Debian 7, Apache, PHP `5.4.39-0+deb7u2`

If I go to _Synchronisation - Backups_ (`contao/main.php?do=syncCto_backups`) and click on any of the links, I am always redirected back to `contao/main.php?do=syncCto_backups` with a `303 See Other` status code.

**Comment by fritzmg** [comment]
Any progress here? It's a bit inconvenient to not be able to use the backup functionality in projects where we also need MetaModels.

**Comment by stefanheimes** [comment]
@fritzmg Yes, we have a commit for it. Can you please test it with the 3.0.0-beta2.

**Comment by fritzmg** [comment]
Yep, works now :)
