### ISSUE TITLE
3.0.5: configuration of hidden tables is not saved

### ISSUE THREAD

**Issue by fritzmg** [menatwork/syncCto#253]
e.g. go to the syncCto configuration, deselect `tl_files` for instance under "hidden tables", save - `tl_files` will still be selected.

**Comment by stefanheimes** [comment]
Hi, you are right, but "it's not a bug it's a feature". 

We have some settings which can not be changed over the backend. Like the tl_files. If you want to change this go into the config file.(https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/config/config.php#L246) 

At this line you will find all Blacklist settings. Edit these lines or better use the initializeSystem hook to change the config. (https://docs.contao.org/books/api/extensions/hooks/initializeSystem.html)

**Comment by fritzmg** [comment]
Oh right, haven't I asked this one already once? :D

**Comment by stefanheimes** [comment]
Try the 3.1.0-beta1. We have add a function for transfering the tl_files. Go to the SyncFrom or SyncTo mask, hit the Database checkbox and wait a moment. After the reoload a checkbox for the "tl_tiles" should be displayed. 

At the moment it is a beta version. But it will help with some problems with the dbafs. 

I you can use it, please tell me if anything works for you.

**Comment by fritzmg** [comment]
I see, thx
