### ISSUE TITLE
client status not updating in ie / error in ping.js

### ISSUE THREAD

**Issue by m-vo** [menatwork/syncCto#257]
The client legend (this round indicator) does not update (shows 'grey' all the time) under ie 11. 

The javascript console outputs an error that points to here:
https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/assets/js/ping.js#L8

``SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "getSiblings" nicht.``

(syncCto 2.6.2)

**Comment by stefanheimes** [comment]
We have change some elements in the system and improved the ajax. But only for the current version. To fix the problem use the new JS:

https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/assets/js/ping.js

If you have still some problems, refresh this ticket.
