### ISSUE TITLE
3.2.0-beta1 fails with '401 Authorization Required'

### ISSUE THREAD

**Issue by m-vo** [menatwork/syncCto#259]
System
- server: 3.2.0-beta1 / windows, PHP 5.6.15
- client A: 3.2.0-beta1 / linux, PHP 5.6.16
- client B: 3.1.0-beta1 / linux, PHP 5.6.16

When trying to do a client-systemcheck in the server backend with client A (same version) it fails with the message:

```` Client error response [url] http://www2.mydomain.de/ctoCommunication.php?engine=aes&act=CTOCOM_HELLO&apikey=QplVrApv8LFBUoTucA[...]&con= [status code] 401 [reason phrase] Authorization Required````

The system log shows those two messages:
- ````Error on synchronization client ID 1````
- ````The client with the adress: seems to be an older Version.````

However, it works for client B (older version). The status icons (on Firefox) don't update as well, maybe because the failing client id is the top one.

**Comment by stefanheimes** [comment]
Fixed in 6287a9557ff001f3d7c2a943c8098f8652000f68
New Version 3.2.0-beta3.

Thx for the issue.

**Comment by stefanheimes** [comment]
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@m-vo could you please have a final look at this and tell if your issue has been resolved?
