### ISSUE TITLE
 Fehlermeldung syncCTO - Konfigurationseinstellungen werden nicht gespeichert

### ISSUE THREAD

**Issue by padgrob** [menatwork/syncCto#266]
Beide Contao Instanzen
Contao Installationen 3.4.0
syncCTO 3.0.5

- Die Installation von SyncCTO bereitete keine Probleme, auch das einrichten des Clients klappt Wunderbar (Status: Alle Systeme sind Online)
- syncCTO Systemcheck --> alles Grün

Unter Konfiguration können nicht alle Einstellungen gespeichert werden. Lösche ich zum Beispiel unter Ordner den Eintrag "assets/css/" und speichere dann die Konfiguration, wird dieser nach dem Speichern wieder angezeigt. Das gleiche Verhalten habe ich auch bei "Dateien" und "Erlaubte Ordner".

Code:
Fatal error: Class 'ContaoCommunityAlliance\Contao\Bindings\Events\Controller\LoadDataContainerEvent' not found in /usr/www/users/stagey/THA/SKODA/velowelt/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Builder/Legacy/DcaReadingDataDefinitionBuilder.php on line 44

Nach der Installation der aktuellen 3.2.0-beta8, ist auch hier der Fehler noch gleich vorhanden.

Ticket hängt mit folgendem Ticket zusammen: https://github.com/menatwork/syncCto/issues/265

**Comment by stefanheimes** [comment]
Moin, 

bezüglich der Konfiguration: It's not a bug it's a feature. Es gibt Elemente in der Konfiguration die nicht entfernt werden könne. Das System schreibt diese Elemente immer wieder rein. Wenn diese Einträge wirklich entfernt werden sollen, kann diese über eine config.php geregelt werden. 

Siehe https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/config/config.php#L248 
Hier sind alle Listen der Konfiguration hinterlegt. Du kannst diese einfach Auskommentieren und dann die Konfiguration im Backend anpassen. Allerdings würde das System nach einem Update die Daten überschreiben. Daher wäre die beste Methode einen zz-"ordner" zu erstellen und die config mit einer eigenen config.php um zu schreiben, damit es update sicher ist.

Wegen dem Fehler, wäre es möglich das ich eine Liste der installierten Paketen bekommen kann, damit ich weiß welche Abhängigkeiten installiert sind?

**Comment by padgrob** [comment]
Hallo 

Ok, danke für die Info, hab das mit einem Bug verwechselt. Anbei eine List mit den Installierten Erweiterungen.

bit3/contao-theme-plus 4.4.3	 

contao			
	contao/core 3.4.0	
	
contao-community-alliance			
	contao-community-alliance/composer-client 0.16.3	 
	contao-community-alliance/meta-palettes 1.9.7	
	
contao-legacy			
	contao-legacy/ce_article_list 1.6.3.9003
	
	contao-legacy/dma_elementgenerator 
		dma/dma_elementgenerator 1.0.3.9006
		
	contao-legacy/pageimage 
		terminal42/contao-pageimage 3.1.3.9007
		
	contao-legacy/rateit 3.4.2.9009	
	
	contao-legacy/rocksolid-slider 
		madeyourday/contao-rocksolid-slider 1.4.1.9005
		
	contao-legacy/stylepicker4ward 
		psi/stylepicker4ward 2.1.3.9005
		
	contao-legacy/teaserimages 2.0.0.9005
	
	contao-legacy/twig 
		bit3/contao-twig 1.6.2.9007
		
	menatwork			
		menatwork/synccto 3.2.0-beta8

Falls noch mehr Informationen gewünscht sind, einfach melden.

Gruess Patrick

**Comment by stefanheimes** [comment]
Moin, 

kannst du  "XX Abhängigkeiten installiert (Abhängigkeitsgraph)" anklicken, damit ich alles sehe und auch die Abhängigkeiten. Dann hab ich das große ganze und kann mal schauen ob es ein Problem mit der Version ist.

**Comment by padgrob** [comment]
Anbei die Screenshots

![1](https://cloud.githubusercontent.com/assets/11654144/14852077/83255aac-0c84-11e6-940b-ffb7aac9a0c7.PNG)
![2](https://cloud.githubusercontent.com/assets/11654144/14852080/879c6c92-0c84-11e6-9b5d-08735b0b9635.PNG)
![3](https://cloud.githubusercontent.com/assets/11654144/14852086/90e5b114-0c84-11e6-99c2-3933fdeb06fd.PNG)
![4](https://cloud.githubusercontent.com/assets/11654144/14852089/924ec5d6-0c84-11e6-8b12-98a07417515d.PNG)

**Comment by stefanheimes** [comment]
Moin, 

mir fällt auf das die "contao-community-alliance/events-contao-bindings" anscheinend nicht installiert sind. Das würde den Fehler erklären. 

Könntest du das einmal prüfen.

**Comment by padgrob** [comment]
Sieht schon mal gut aus! Die Fehlermeldung erscheint nicht mehr. Ich teste mal kurz alles und melde mich wieder.

**Comment by padgrob** [comment]
Beim Backup krieg ich keine Fehlermeldung mehr. Wenn ich den Client Synchronisieren will erhalte ich nun den Fehler:

Fatal error: Call to a member function hasErrors() on a non-object in /usr/www/users/stagey/THA/SKODA/velowelt/system/modules/generalDriver/templates/dcbe_general_field.html5 on line 17

**Comment by stefanheimes** [comment]
Schau mal ob du in system/modules 2 mal einen Ordner hast der iwie dc-general heißt. Wenn ja dann haben wir den Fehler.

**Comment by stefanheimes** [comment]
Wenn ja, sind das die Altlasten. Der Ordner generalDriver ist falsch du solltest unter system/modules auch noch einen Ordner mit dem Namen dc-general haben. Wenn ja kannst du den anderen generalDriver einmal sichern und dann entfernen. Danach sollte alles gehen.

**Comment by padgrob** [comment]
Hallo 

Der Ordner dc-general ist nur einmal vorhanden. denn Ordner generalDriver habe ich mal gesichert und entfernt. Dann habe ich bereits schon mal keine Fehlermeldung mehr erhalten aber der Sync hat auch noch nicht funktioniert.

Ich habe nun noch die Erweiterung events-contao-bindings von 3.5.0 alpha1 auf die aktuelle 3.5.1 und synccto von 3.2.0beta-8 wieder auf die stabile 3.0.5 angepasst. Nun scheint es zu funktionieren

**Comment by padgrob** [comment]
So, konnte den Sync nun korrekt einrichten und testen. Nun funktioniert alles Wunderbar.
Vielen Dank für deine Hilfe und ein schönes langes Wochenende.

Gruss Patrick
