### ISSUE TITLE
API key marked as false with every attempted sync (on one specific host)

### ISSUE THREAD

**Issue by mirkokienle** [menatwork/syncCto#273]
(Replicating issue from E-Mail thread)

With a web host we haven't used before (required by the client; hostpoint.ch) syncCto always marks the connection as broken due to an incorrect API key, though the key is correct and has been checked and newly generated multiple times. System check marks everything as OK except MySQL trigger (which shouldn't be required for the free version).

Versions: Contao 3.5.23, syncCto 3.2.0-beta11

Attempted measures:
- Set up connection loop by adding server as its own client. Same result.
- Tried various combinations of disabling handshake and changing encryption method. No change.
- Enabled debug mode. No helpful results, no debug log file generated.

Error code:
Client error response [url] http://www.*****.ch/ctoCommunication.php?engine=aes&act=CTOCOM_HELLO&apikey=rJnuhvVdsrZGFo3Z8Eat7XxAfI608trq44cU9KzELxUuPgcGbJHAhgwWx2ElnlD1SFxokQLRAI2xN9hG%2BmZ6y77z0WqxRTpcko4%2F61Q8tkCni04%3D&con= [status code] 400 [reason phrase] Bad

**Comment by stefanheimes** [comment]
Hi, i can't say what is wrong. Have you take a look in the logs from the Server. The HTTP Server didn't accept the request. So it could be that the php isn't called because the server denied the request. 

But take a look in the Systemlog in the backend from Contao. Maybe there is a entry from ctoCommunication.

**Comment by mirkokienle** [comment]
Whatever the problem was, it seems to have disappeared with syncCto 3.2.2 – alle connections are now going through. I'll reopen the issue if the problem rears its head again.

**Comment by stefanheimes** [comment]
Maybe this was the fix https://github.com/menatwork/ctoCommunication/commit/a306fc6597bcf1b812ceebd1465e728375f10dd9

**Comment by mirkokienle** [comment]
Im afraid I've run into the same problem. What's particularly demoralizing is that the problem has now shown itself on a local-remote setup which still has installations which run fine, on a host that didn't have any problems until now.

The server-side log gives me this error:

`[22-Feb-2017 08:50:13 Europe/Zurich] PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Could not find the delimiter in the response.' thrown in /home/.../composer/vendor/menatwork/ctocommunication/system/modules/ctoCommunication/src/CtoCommunication/Codifyengine/Base.php on line 105
#0 /home/.../composer/vendor/menatwork/ctocommunication/system/modules/ctoCommunication/src/CtoCommunication/Codifyengine/AES.php(70): CtoCommunication\Codifyengine\Base->splitText(false)
#1 /home/.../composer/vendor/menatwork/ctocommunication/system/modules/ctoCommunication/src/CtoCommunication/Serivces/Client.php(130): CtoCommunication\Codifyengine\AES->Decrypt(false)
#2 /home/.../ctoCommunication.php(19): CtoCommunication\Serivces\Client->run()
#3 {main}`
