### ISSUE TITLE
Liste nicht empfohlener Tabellen leer - kein DB-Backup

### ISSUE THREAD

**Issue by FRappsil** [menatwork/syncCto#280]
Bin gerade beim Test des Abgleichs von unserem Entwicklungs- ins Produktivsystem mittels syncCto. Dabei ist mir aufgefallen, dass unter Konfiguration die Liste der nicht empfohlenen Tabellen leer ist:
![nicht_empfohlene_tabellen_leer](https://user-images.githubusercontent.com/29429097/29510160-1caea416-865b-11e7-8f6b-3166e7dedf4c.JPG)

Das ist ja vielleicht nicht schlimm, aber das Produktivsystem wird nicht aktualisiert (ohne Fehlermeldung) und ein einfaches DB-Backup ist leider auch nicht möglich. Hier findet syncCto keine Tabellen:
![datenbankbackup_keine_tabellen](https://user-images.githubusercontent.com/29429097/29510162-1e5f41ee-865b-11e7-8481-ff3c3bf70200.JPG)

Woran liegt das?

**Comment by stefanheimes** [comment]
Könntest du mir einmal die Version geben von Contao und der SyncCto Version und ob ihr das ER oder Composer benutzt. Danke.

**Comment by FRappsil** [comment]
Hallo Stefan,

Contao: 3.5.28
SyncCto: 2.7.0-beta1 Build 5
ZipArchiveCto: 1.1.0 Build 19
phpseclib: 0.3.1 Build 21
diffiehellmann: 0.3.0 Build 18
ctoCommunication: 1.2.5 Build 3

Hoffe, ich hab alles erwischt. Wir nutzen ausschließlich das ER.

**Comment by FRappsil** [comment]
Problem gelöst - Ursache unklar.

Wir haben unser Contao-System neu aufgesetzt und damit funktioniert jetzt auch wieder das Backup und der Abgleich zu Prod. Die Ursache ist aber unklar. Ticket kann aus meiner Sicht geschlossen werden.
