### ISSUE TITLE
compatibility to 4.4.x

### ISSUE THREAD

**Issue by mammut47** [menatwork/syncCto#282]
No compatibility to Contao 4.4.x. Are there plans for new LTS Version of Contao?

**Comment by richardhj** [comment]
I share my thoughts (my personal idea) for Contao 4 here:

syncCto should no longer transfer the files as hitherto. Rather it should enforce a git repository for the root directory with a proper `.gitignore` since the `.gitignore` for the current Contao 4.4.x managed edition is cumbersome.
syncCto should then, as I imagine, just be a "git wrapper" for the file system.
The database sync should be continued as it is, this worked very well for me the last times.

**Comment by stefanheimes** [comment]
We have make some plans. 

First we want to release a simple version of SyncCto. This means we only change the things we have to change. For example, we have to update the ctoCommunication to work with symfony and routes. We have to replace the Diffie Hellman Key Exchange with a one with composer support. 

This "new" version will only support the content. This means, only the database sync and the files from the tl_files folder will be syncronized. 

After this we want to refactor the system. 

Final Step is a version which works with symfony and maybe a standalon version.

**Comment by mammut47** [comment]
Do you see a time horizon for that?

**Comment by stefanheimes** [comment]
Not yet. We investigating how much time we need to make this changes. After this we can make a timeline.

**Comment by ikahai** [comment]
Same....any updates on that issue?

**Comment by stefanheimes** [comment]
Hi there, next wednesday i'll have a call with all developers of the project. After this call i hope to have a time when the new version is ready for release.

**Comment by frontendschlampe** [comment]
That would be great! Thx.

**Comment by thepixture** [comment]
Sounds great!

**Comment by mstaack** [comment]
@stefanheimes are there any new infos regarding sync with 4.4?
Thanks Max

**Comment by mammut47** [comment]
In August 2018, I got a call from someone from 'Men At Work" saying that the development for synccto and Contao 4.4.x would be finished soon.
So far I find nothing about it.
Even in the repositories for Contao 4.4.x is still nothing to find.
Are there any news regarding sync with contao 4.4.x?

**Comment by andyKempf** [comment]
@mammut47 Meanwhile there is a feature branch for SyncCTO 4, still in the BETA phase, but with support for the current LTS version. The current last commit is from September 1st.
https://github.com/menatwork/syncCto/tree/feature/contao4
Mega awesome!

**Comment by davidmaack** [comment]
Sorry that things took so long, one programmer who wanted to support us let us down and an internal repro got corrupted so some of the changes got lost on the way. As AndyKempf mentioned already, there is a beta version available now, please see the #284 for further information.

**Comment by andyKempf** [comment]
Don't worry, but it's great to continue working on this great tool. This allows a comfortable and professional deployment process in Contao if you have a test, staging and production system.

**Comment by stefanheimes** [comment]
He there i will close this issue. Please use issue #284 instead.
