### ISSUE TITLE
Communication-Key angeblich inkorrekt

### ISSUE THREAD

**Issue by felixpfeiffer** [menatwork/syncCto#302]
Moin,
ich habe zwei Contao 4.10 Installationen, die auf dem selben Server liegen. In beiden ist SyncCto in Version 4.0.2 vom 31.08. installiert. Trotz mehrmals neuer Erstellung des Communication-Key und einfügen dieses in die andere Installation bekomme ich immer die Meldung, der Key sei inkorrekt. Beim Aufruf der Synchronisation kommt dann die Meldung: 
Der Client meldet folgenden Fehler:
Unknown RPC Call

RPC Call: SYNCCTO_VERSION

Die Seiten liegen bei AllInkl unter php 7.4, Zertifikat ist ein Let's Encrypt. URL und Port stimmen. 

Vielleicht hat jemand eine Idee, woran es liegen könnte.
Danke,
Felix

**Comment by frontendschlampe** [comment]
Mach mal ein Update - siehe https://github.com/menatwork/syncCto/pull/301 - dann sollte es wieder gehen

**Comment by felixpfeiffer** [comment]
Perfekt! Danke für den Hinweis!
