### ISSUE TITLE
Any plans for PHP 8.1 and Contao 5?

### ISSUE THREAD

**Issue by HoTodo** [menatwork/syncCto#323]
This is not an issue but merely a question:
Are there any plans to make this extension usable with PHP 8.1 and Contao 5 from your side?

No offence meant. I'm just wondering whether I can wait for this extension to become compatible or if I have to evaluate alternative ways to organize my deployments.

By the way:
This extension brought me into Contao in the first place. It would sad if it is discontinued now. 
(I'd love to see it as a core module. This would set Contao miles ahead of any other CMS. :-) )

**Comment by JLBA** [comment]
I absolutely agree with the last sentence. How customizable Contao would be with Metamodels as a core module. (News and Events modules could just be made with MM.)

Le 15 février 2023 10:24:52 GMT+01:00, HoTodo ***@***.***> a écrit :
>(I'd love to see it as a core module. This would set Contao miles ahead of any other CMS. :-) )

**Comment by zonky2** [comment]
First of all, with Contao 4.14 and PHP 8.1, syncCto runs as version 4.1.

For Contao 5 there will be an alternative project elsewhere.

btw: if you want to have MetaModels in the "core", you should rather work with Drupal, OctoberCMS, Silverstripe... there are also other CMS like Typo3 that have a staging system in the core.

With Contao, you have to add all this as an extension, which is not always possible without "pain".

Nevertheless, Contao is a great CMS :D

**Comment by HoTodo** [comment]
From what you wrote I can answer my own question:
No, the extension will not work with Contao 5.


Last friday (17.02.2023) the extension was updated to be compatible to PHP ^8.0
That's nice for new installations. With the dropped backward compatibility to PHP 7 it could force existing installations to migrate to PHP 8 (which is a good thing).


So I will investigate other, more generic ways to deploy my local installation to the customers server.

When I started looking into Contao, I was hoping for a more elegant and long lasting  way other than backup-copy-restore.
But I will stay with Contao, even though the backend UI is a bit old fashioned and the UX is rather clunky at times.

I really like that it has so many useful core modules out of the box.
(I thought in the beginning synchronization was one of them - that's why I started with Contao.)

**Comment by JLBA** [comment]
> Nevertheless, Contao is a great CMS :D

Hi Zonky,
Sorry, I confused SyncCto and MM (which are both great extensions...) And you're right, MM is to big to be easily integrated as core module. Another one could be : agoat/contao-customcontentelements.

And i'm still ok that Contao is a great CMS. i don't want to work with another one. -)
