### ISSUE TITLE
Keine Synchronisation mehr möglich

### ISSUE THREAD

**Issue by iCodr8** [menatwork/syncCto#91]
Ich habe vorhin versucht die Verschlüsselungsmethoden zu testen und erhalte nun andauernd die folgende Error-Nachricht:

> There was an error on client site with message:
> 
> Public key is not a natural number
> 
> RPC Call: CTOCOM_START_HANDSHAKE | Class: CtoComRPCFunctions | Function: startHandshake

Momentan ist keine Verschlüsselung eingestellt. Die ctoCommunication Key stimmen überein.

**Comment by m-vo** [comment]
Das Problem ist in syncCto 2.6.2 noch vorhanden: Server 1: nur BC Math, Server 2 BC Math und GMP. Der Schlüsseltausch funktionierte erst nachdem ich auf Server 1 auch GMP aktiviert habe,
